#!/usr/bin/env bash

install_python() {
  echo "Installing Python"
  if [ "$(uname)" == "Darwin" ]; then
    brew install python3
    pip install numpy
    pip install imutils
    pip install opencv-python
    pip install base64
    pip install argparse
    pip install IPython
    pip install tqdm
    pip install subprocess
    pip install requests
    pip install datetime
    pip install python-dotenv
    pip install pathlib
    pip install django-imagekit
    pip install imagekitio
  else
    sudo apt-get update
    sudo apt-get install python3
    pip install numpy
    pip install imutils
    pip install opencv-python
    pip install base64
    pip install argparse
    pip install IPython
    pip install tqdm
    pip install subprocess
    pip install requests
    pip install datetime
    pip install python-dotenv
    pip install pathlib
    pip install django-imagekit
    pip install imagekitio
  fi
}

# install python 3.6
command -v python > /dev/null 2>&1
if [ $? -eq 0 ]; then
  echo "python already installed"
else
  install_python
fi

